/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */
import type { CommonEnumsApiResultStatusCode } from './commonEnumsApiResultStatusCode';
import type { FluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798e } from './fluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798e';

export interface CommonBaseApiResult1FluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798eFluentResultsVersion3500CultureNeutralPublicKeyTokenNull {
  isSuccess?: boolean;
  statusCode?: CommonEnumsApiResultStatusCode;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  warnings?: string[] | null;
  data?: FluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798e;
}
