/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */
import type { FluentResultsIReason } from './fluentResultsIReason';
import type { FluentResultsIError } from './fluentResultsIError';
import type { FluentResultsISuccess } from './fluentResultsISuccess';

export interface FluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798e {
  readonly isFailed?: boolean;
  readonly isSuccess?: boolean;
  /** @nullable */
  readonly reasons?: readonly FluentResultsIReason[] | null;
  /** @nullable */
  readonly errors?: readonly FluentResultsIError[] | null;
  /** @nullable */
  readonly successes?: readonly FluentResultsISuccess[] | null;
  readonly valueOrDefault?: boolean;
  readonly value?: boolean;
}
