/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */
import type { InsuranceBusinessModelsCustomerResidenceInquiryEnum } from './insuranceBusinessModelsCustomerResidenceInquiryEnum';

export type GetApiV1CustomerAuthenticationUserGetParams = {
CustomerId?: string;
ResidenceInquiry?: InsuranceBusinessModelsCustomerResidenceInquiryEnum;
};
