/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */
import type { InsuranceBusinessCommonEnumPolicyStatus } from './insuranceBusinessCommonEnumPolicyStatus';

export type GetApiV1CustomerPolicyGetParams = {
'Filter.AgentId'?: string;
'Filter.AgentName'?: string;
'Filter.CustomerId'?: string;
'Filter.MobilePhone'?: string;
'Filter.NationalId'?: string;
'Filter.CompanyNationalId'?: string;
'Filter.PolicyNo'?: string;
'Filter.CentralInsuranceNO'?: string;
'Filter.status'?: InsuranceBusinessCommonEnumPolicyStatus;
'Filter.Search'?: string;
'Pagination.Size'?: number;
'Pagination.Page'?: number;
'Pagination.Sort'?: string;
};
