/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */

export * from './commonBaseApiResult';
export * from './commonBaseApiResult1FluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798eFluentResultsVersion3500CultureNeutralPublicKeyTokenNull';
export * from './commonEnumsApiResultStatusCode';
export * from './fluentResultsIError';
export * from './fluentResultsIErrorMetadata';
export * from './fluentResultsIReason';
export * from './fluentResultsIReasonMetadata';
export * from './fluentResultsISuccess';
export * from './fluentResultsISuccessMetadata';
export * from './fluentResultsResult1SystemBooleanSystemPrivateCoreLibVersion8000CultureNeutralPublicKeyToken7cec85d7bea7798e';
export * from './getApiV1CustomerAuthenticationUserGetParams';
export * from './getApiV1CustomerPolicyGetParams';
export * from './insuranceBusinessCommonEnumPolicyStatus';
export * from './insuranceBusinessModelsCustomerResidenceInquiryEnum';
export * from './insuranceBusinessPortalCustomerPolicyCommonRequestCustomerDetailFilterRequest';
export * from './insuranceBusinessPortalGeneralAuthenticationCommonRequestSendCodeRequest';
export * from './insuranceBusinessPortalGeneralAuthenticationCommonRequestVerifyCodeRequest';