/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * API V1
 * <h2>Sample data for test api(s)</h2><br/><hr/><strong>Username : user</strong><br/><strong>Password : pass</strong><br/><strong>Mobile : 0919********</strong><br/><hr/>
 * OpenAPI spec version: v1
 */

export type InsuranceBusinessCommonEnumPolicyStatus = typeof InsuranceBusinessCommonEnumPolicyStatus[keyof typeof InsuranceBusinessCommonEnumPolicyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsuranceBusinessCommonEnumPolicyStatus = {
  Draft: 'Draft',
  Replaced: 'Replaced',
  Publish: 'Publish',
  Recheck: 'Recheck',
  Expired: 'Expired',
  InitialRegistration: 'InitialRegistration',
  ReadyToCallSanhabApi: 'ReadyToCallSanhabApi',
  WaitForInquiry: 'WaitForInquiry',
  CallSanhabAPI: 'CallSanhabAPI',
  Proposal: 'Proposal',
  ConfirmCheque: 'ConfirmCheque',
  Canceled: 'Canceled',
} as const;
